---
all:
  hosts:
    spark-0f0b:
      ansible_host: spark-0f0b.shawndo.intra
    spark-6d14:
      ansible_host: spark-6d14.shawndo.intra
  vars:
    ansible_user: sdrew
    ansible_python_interpreter: /usr/bin/python3
